config/routes.rb
Rails.application.routes.draw do

  get '/login' => 'admin/sessions#new'
  get '/logout' => 'admin/sessions#destroy'
  
  root 'posts#index'
  namespace :admin do
    resources :posts
    resources :settings, only: [:new, :edit, :update, :create]
    resources :dashboard, only: [:index]
    resources :notifications, only: [:index, :destroy]
    resources :messages, only: [:index, :show, :update, :destroy]
    resources :visitors, only: [:index, :destroy]
    resources :comments, only: [:index, :update, :destroy]
    resources :tags, except: [:index]
    resources :sessions, only: [:new, :create, :destroy]
    resources :moderators, only: [:index, :edit, :update]
  end
  # resources :moderators, module: 'admin'
  
  resources :posts, only: [:index, :show]
  resources :messages, only: [:new, :create]
  resources :comments, only: [:create]

  match 'dismiss_all_notifications', to: 'admin/notifications#delete_all', via: :delete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :visitor
  has_many :notifications, as: :notifiable, dependent: :destroy

  validates :message, presence: true

  scope :approved, -> { where status: true }

  def self.matching_fullname_or_message params
    joins(:visitor).where("fullname LIKE ? OR message LIKE ?", "%#{params}%", "%#{params}%")
  end
  
  include Notifiable  
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :visitor

  validates :content, presence: true

  def self.matching_fullname_or_content params
    joins(:visitor).where("fullname LIKE ? OR content LIKE ?", "%#{params}%", "%#{params}%")
  end

  def mark_read
    update(status: true) if status == false
  end
end

app/models/moderator.rb
class Moderator < ApplicationRecord
  has_secure_password

  has_many :posts

  validates :fullname, presence: true
  validates :username, presence: true, format: {with: /@/, message: 'is not valid'}
  validates :password, presence: true
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :notifiable, polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags
  belongs_to :moderator

  validates :title, presence: true
  validates :content, presence: true

  scope :published, -> { where(publish: true).order(id: :desc) }

  def self.matching_title_or_content search
    where("title LIKE ? OR content LIKE ?", "%#{search}%", "%#{search}%")
  end

  def self.filter_by_tags param_tag
    includes(:tags).where(publish: true, tags: {name: param_tag}).order(id: :desc)
  end
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/setting.rb
class Setting < ApplicationRecord
  def self.site_name
     Setting.first.try(:site_name) ? Setting.first.site_name : "Site name here"
  end

  def self.post_per_page
    Setting.first.try(:post_per_page)
  end

  def self.tag_visible?
    Setting.first.try(:tag_visibility)
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tags
  has_many :posts, through: :post_tags

  validates :name, presence: true
  def in_use?
    PostTag.exists?(tag_id: self.id)
  end  
end

app/models/visitor.rb
class Visitor < ApplicationRecord
  has_many :notifications, as: :notifiable, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :messages, dependent: :destroy

  validates :fullname, presence: true
  validates :email, format: { with: /@/, message: 'is not valid' }

  accepts_nested_attributes_for :comments
  accepts_nested_attributes_for :messages

  include Notifiable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    if visitor.save
      flash[:notice] = "Successfully created new comment"
    else
      flash[:alert] = "There was a problem creating your comment"
      set_visitor_sessions
    end

    redirect_back(fallback_location: root_path)
  end

  private

  def visitor_comments_params
    params.require(:visitor).permit(:fullname, :email, :comments_attributes => [:message, :post_id])
  end

  def visitor
    @visitor ||= VisitorCommentService.new(visitor_comments_params).visitor
  end

  def set_visitor_sessions
    session[:visitor_errors] = visitor.errors.full_messages
    session[:visitor_params] = visitor_comments_params
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @visitor_message = Visitor.new(messages: [Message.new])
  end

  def create
    if visitor.save
      flash[:notice] = "Successfully sent your message"
      redirect_to new_message_path
    else
      @visitor_message = visitor
      render :new
    end
  end

  def strong_params
    params.require(:visitor).permit(:fullname, :email, messages_attributes: [:content])
  end

  def visitor
    @visitor ||= VisitorMessageService.new(strong_params).visitor
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  after_action :clear_sessions, only: [:show]

  def index
    if params[:tag]
      @posts = Post.filter_by_tags(params[:tag]).page(params[:page]).per(Setting.post_per_page)
    else
      @posts = Post.published.page(params[:page]).per(Setting.post_per_page)
    end
  end

  def show
    @post = Post.find(params[:id])
    @visitor_comment = visitor_comment
  end

  private

  def clear_sessions
    [:visitor_errors].each { |k| session.delete(k) }
  end

  def visitor_comment
    if session[:visitor_errors]
      VisitorCommentService.new(session[:visitor_params]).visitor
    else
      Visitor.new(comments: [Comment.new])    
    end
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
  def create_deletable_button tag 
    if tag.in_use?
      link_to '#' do
        # this is cuz we can't use html in the ruby file
        content_tag(:button, 'Delete', class: 'disabled')
      end
    else
      link_to admin_tag_path(tag), method: :delete, data: { confirm: 'Are you sure?' } do
        content_tag(:button, 'Delete')
      end
    end
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def status_converter(status, truthy: 'Active', falsey: 'Pending')
    if status
      truthy
    else
      falsey
    end
  end

  def time_ago time
    "#{time_ago_in_words(time)} ago"
  end

  def double_digit_number n
    '%02d' % n
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/shared/_admin-nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to Setting.site_name, posts_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active">
					<%= link_to admin_dashboard_index_path do %>
						Dashboard <span class="sr-only">(current)</span>
					<% end %>
				</li>
				<li><%= link_to 'Posts', admin_posts_path %></li>
				<li><%= link_to 'Moderators', admin_moderators_path %></li>
				<li><%= link_to 'Tags', new_admin_tag_path %></li>
				<li><%= link_to 'Comments', admin_comments_path %></li>
				<li><%= link_to 'Visitors', admin_visitors_path %></li>
				<li><%= link_to 'Messages', admin_messages_path %></li>
				<li><%= link_to 'Notifications', admin_notifications_path %></li>
				<li><%= link_to 'Setting', new_admin_setting_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if session[:current_moderator_id] %>
          <li><%= link_to 'Logout', logout_path %></li>
        <% else %>
          <li><%= link_to 'Login', login_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to Setting.site_name, posts_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active">
					<%= link_to posts_path do %>
						Posts <span class="sr-only">(current)</span>
					<% end %>
        </li>
        <li><%= link_to 'About', "#" %></li>
        <li><%= link_to 'Contact', new_message_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if session[:current_moderator_id] %>
          <li><%= link_to 'Admin',  admin_dashboard_index_path %></li>
          <li><%= link_to 'Logout', logout_path %></li>
        <% else %>
          <li><%= link_to 'Login', login_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>