config/routes.rb
Rails.application.routes.draw do

  get '/login' => 'admin/sessions#new'
  get '/logout' => 'admin/sessions#destroy'
  
  root 'posts#index'
  namespace :admin do
    resources :posts
    resources :settings, only: [:new, :edit, :update, :create]
    resources :dashboard, only: [:index]
    resources :notifications, only: [:index, :destroy]
    resources :messages, only: [:index, :show, :update, :destroy]
    resources :visitors, only: [:index, :destroy]
    resources :comments, only: [:index, :update, :destroy]
    resources :tags, except: [:index]
    resources :sessions, only: [:new, :create, :destroy]
    resources :moderators, only: [:index, :edit, :update]
  end
  # resources :moderators, module: 'admin'
  
  resources :posts, only: [:index, :show]
  resources :messages, only: [:new, :create]
  resources :comments, only: [:create]

  match 'dismiss_all_notifications', to: 'admin/notifications#delete_all', via: :delete
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags
  belongs_to :moderator

  validates :title, presence: true
  validates :content, presence: true

  scope :published, -> { where(publish: true).order(id: :desc) }

  def self.matching_title_or_content search
    where("title LIKE ? OR content LIKE ?", "%#{search}%", "%#{search}%")
  end

  def self.filter_by_tags param_tag
    includes(:tags).where(publish: true, tags: {name: param_tag}).order(id: :desc)
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]

  def index
    if params[:search].present?
      @posts = Post.matching_title_or_content(params[:search]).page params[:page]
      # @posts = Post.where("title LIKE ? OR content LIKE ?", "%#{params[:search]}%", "%#{params[:search]}%").page params[:page]
    else
      @posts = Post.all.order(id: :desc).page params[:page]
    end
  end

  def show    
  end  

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.moderator_id = current_moderator.id
    if @post.save
      redirect_to admin_posts_url, notice: 'Post was successfully created'
    else
      flash[:alert] = 'There was a problem creating post'
      render :new
    end
  end

  def edit
    
  end

  def update    
    if @post.update(post_params)
      redirect_to admin_posts_url, notice: 'Post was successfully updated'
    else
      flash[:alert] = 'There was a problem updating post'
      render :edit
    end
  end

  def destroy    
    @post.destroy
    flash[:notice] = 'Post was successfully deleted'
    redirect_back(fallback_location: root_path)
  end

  private

  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:id, :title, :content, :publish, tag_ids: [])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  after_action :clear_sessions, only: [:show]

  def index
    if params[:tag]
      @posts = Post.filter_by_tags(params[:tag]).page(params[:page]).per(Setting.post_per_page)
    else
      @posts = Post.published.page(params[:page]).per(Setting.post_per_page)
    end
  end

  def show
    @post = Post.find(params[:id])
    @visitor_comment = visitor_comment
  end

  private

  def clear_sessions
    [:visitor_errors].each { |k| session.delete(k) }
  end

  def visitor_comment
    if session[:visitor_errors]
      VisitorCommentService.new(session[:visitor_params]).visitor
    else
      Visitor.new(comments: [Comment.new])    
    end
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<h1>Posts</h1>
<%=  link_to 'All Posts', posts_path %>
<% @posts.each do |post| %>
	<p>
		<%= truncate(post.title, length: 70, separator: ' ') %> <br>
		<%= time_ago post.created_at %>
	</p>
	<p>
		<%= truncate(post.content, length: 50, separator: ' ') { link_to 'Read More', post_path(post)} %>
	</p>

	<% if Setting.tag_visible? %>
	<h2>Tags</h2>
		<p>
			<% post.tags.each do |tag| %>
				<%= link_to tag.name, posts_path(tag: tag.name) %>
			<% end %>
		</p>
	<% end %>
	<hr>
<% end %>

<%= paginate @posts %>

app/views/posts/show.html.erb
<h1>Posts</h1>
<%= link_to 'All Posts', posts_path %>

<p>
	<%= @post.title %>
	<%= time_ago @post.created_at %>
</p>

<p>
	<%= @post.content %>
</p>

<h3>Comments</h3>
<p>	
	<% @post.comments.approved.each.with_index(1) do |comment, index| %>
	<p>		
		<%= comment.message %> <b><%= double_digit_number(index) %></b> <br>
		<b><%= comment.visitor.fullname %></b> commented: <%= time_ago comment.created_at %>
	</p>
	<% end %>
</p>
<hr>

<%= form_for @visitor_comment, url: comments_url do |f| %>
	<% if session[:visitor_errors] %>
		<div id="error_explanation">
			<h2><%= pluralize(session[:visitor_errors].count, "error") %> prohibited this comment from being saved:</h2>
			<ul>
				<% session[:visitor_errors].each do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<p>
		<%= f.label :fullname %>
		<%= f.text_field :fullname %>
	</p>
	<p>
		<%= f.label :email %>
		<%= f.text_field :email %>
	</p>
	<%= f.fields_for :comments do |c| %>
		<p>
			<%= c.label :message %>
			<%= c.text_area :message %>
			<%= c.hidden_field :post_id, value: @post.id %>
		</p>
		<p>
			<%= f.submit 'Add Comment' %>
		</p>
	<% end %>
<% end %>